In [9]:
import torch
import numpy as np

# 1. Create the following tensors:
#    a. A scalar tensor with the value 7.
#    b. A 1D tensor (vector) containing the numbers [2, 4, 6, 8, 10].
#    c. A 2D tensor (matrix) with the following rows: [1, 2, 3], [4, 5, 6].
#    d. A 3D tensor with the shape (2, 2, 3) containing any values you like.
scalar_tensor = torch.tensor(7)
vector_tensor = torch.tensor([2, 4, 6, 8, 10])
matrix_tensor = torch.tensor([[1, 2, 3],
                              [4, 5, 6]])
tensor_3d = torch.tensor([
                         [
                         [1,2,3],
                         [3,4,4]
                         ],
                         [
                         [1,2,3],
                         [3,4,4]
                         ]
])

# 2. Print the shape of each of the tensors you created above.
print("Shape of scalar_tensor:", scalar_tensor.shape)
print("Shape of vector_tensor:", vector_tensor.shape)
print("Shape of matrix_tensor:", matrix_tensor.shape)
print("Shape of tensor_3d:", tensor_3d.shape)

# 3. Reshape the matrix_tensor into a 1D tensor. Print the shape of the reshaped tensor.
reshaped_tensor = matrix_tensor.flatten()
print("Shape of reshaped_tensor:", reshaped_tensor)

# 4. Perform the following element-wise operation: Add 5 to each element of the vector_tensor.
added_vector = vector_tensor + 5
print("Added vector:", added_vector)

# 5. Perform matrix multiplication of matrix_tensor with its transpose. Print the resulting tensor.
transposed_matrix = torch.transpose(matrix_tensor, 0, 1)
multiplied_matrix = transposed_matrix @ matrix_tensor
print("Multiplied matrix:", multiplied_matrix)

# 6. Create a NumPy array of shape (3, 3) with random integer values between 1 and 10.
numpy_array = np.random.randint(1, 11, size=(3, 3))
print("NumPy array:\n", numpy_array)

# 7. Convert the NumPy array to a PyTorch tensor.
pytorch_from_numpy = torch.tensor(numpy_array, dtype=torch.int64)
print("PyTorch tensor from NumPy:\n", pytorch_from_numpy)

# 8. Change the data type of the PyTorch tensor to torch.float32. Print the data type of the new tensor.
float_tensor = pytorch_from_numpy.float()
print("Data type of float_tensor:", float_tensor.dtype)

Shape of scalar_tensor: torch.Size([])
Shape of vector_tensor: torch.Size([5])
Shape of matrix_tensor: torch.Size([2, 3])
Shape of tensor_3d: torch.Size([2, 2, 3])
Shape of reshaped_tensor: tensor([1, 2, 3, 4, 5, 6])
Added vector: tensor([ 7,  9, 11, 13, 15])
Multiplied matrix: tensor([[17, 22, 27],
        [22, 29, 36],
        [27, 36, 45]])
NumPy array:
 [[ 6 10  9]
 [ 8  6  4]
 [10  3  3]]
PyTorch tensor from NumPy:
 tensor([[ 6, 10,  9],
        [ 8,  6,  4],
        [10,  3,  3]])
Data type of float_tensor: torch.float32
