In [3]:
import torch

torch_scalar = torch.tensor(3.14)  # Scalar value updated to 3.14
torch_vector = torch.tensor([2, 4, 6, 8])  # Vector with new values
torch_matrix = torch.tensor([[12, 14],  # 2D Matrix updated with different values
                             [16, 18],
                             [20, 22],
                             [24, 26]])   
torch_tensor3d = torch.tensor([  # 3D Tensor with new values
                             [ 
                             [ 0, 2, 4], 
                             [ 6, 8, 10], 
                             ], 
                             [ 
                             [12, 14, 16], 
                             [18, 20, 22], 
                             ], 
                             [ 
                             [24, 26, 28], 
                             [30, 32, 34], 
                             ], 
                             [
                             [36, 38, 40],
                             [42, 44, 46],
                             ] 
                               ])

In [4]:
print(torch_scalar.shape) 
print(torch_vector.shape) 
print(torch_matrix.shape) 
print(torch_tensor3d.shape)

torch.Size([])
torch.Size([4])
torch.Size([4, 2])
torch.Size([4, 2, 3])


In [5]:
import numpy as np
import torch

# Create a random NumPy array
x_np = np.random.random((3, 5))  # 3 rows, 5 columns
print(x_np)
# Example output (values will be random):
# [[0.56347291 0.17683452 0.84931799 0.94718427 0.26507189]
#  [0.04859423 0.35608158 0.91547634 0.70918372 0.12945809]
#  [0.31789047 0.93812456 0.25783918 0.15896174 0.79729465]]

# Convert the NumPy array to a PyTorch tensor
x_pt = torch.tensor(x_np)
print(x_pt)
# Example output (values will be random):
# tensor([[0.5635, 0.1768, 0.8493, 0.9472, 0.2651],
#         [0.0486, 0.3561, 0.9155, 0.7092, 0.1295],
#         [0.3179, 0.9381, 0.2578, 0.1590, 0.7973]], dtype=torch.float64)

[[0.80414286 0.08650698 0.85828411 0.81534665 0.6955122 ]
 [0.73797532 0.40303434 0.40230631 0.29161209 0.74205916]
 [0.29727088 0.39566314 0.6779999  0.53423313 0.72735986]]
tensor([[0.8041, 0.0865, 0.8583, 0.8153, 0.6955],
        [0.7380, 0.4030, 0.4023, 0.2916, 0.7421],
        [0.2973, 0.3957, 0.6780, 0.5342, 0.7274]], dtype=torch.float64)


In [8]:
print(x_np.dtype, x_pt.dtype) 

x_np = np.asarray(x_np, dtype=np.float32)   
x_pt = torch.tensor(x_np, dtype=torch.float32) 
print(x_np.dtype, x_pt.dtype) 

float64 torch.float64
float32 torch.float32


In [9]:
b_np = (x_np > 0.5) 
print(b_np) 
print(b_np.dtype) 

b_pt = (x_pt > 0.5) 
print(b_pt) 
print(b_pt.dtype) 


[[ True False  True  True  True]
 [ True False False False  True]
 [False False  True  True  True]]
bool
tensor([[ True, False,  True,  True,  True],
        [ True, False, False, False,  True],
        [False, False,  True,  True,  True]])
torch.bool


In [ ]:
b_np = (x_np > 0.5) 
print(b_np) 
print(b_np.dtype) 

[[False True True False]
 [False True False True]
 [False False True False]
 [False False False True]]
bool

b_pt = (x_pt > 0.5) 
print(b_pt) 
print(b_pt.dtype) 
tensor([[False,  True,  True, False],
        [False,  True, False,  True], 
        [False, False,  True, False], 
        [False, False, False,  True]]) 
torch.bool

In [10]:
# Create tensor
x = torch.tensor([[1., 2., 3.], [4., 5., 6.]])

# 1. Indexing and Slicing
print(x[0])              #  tensor([1., 2., 3.]) → First row
print(x[:, 1])           #  tensor([2., 5.]) → Second column

tensor([1., 2., 3.])
tensor([2., 5.])


In [11]:
# 2. Tensor Creation
zeros = torch.zeros((2, 3))
ones = torch.ones((2, 3))
rand = torch.rand((2, 3))
eye = torch.eye(3)
print(zeros)             #  All zeros
print(ones)              #  All ones
print(rand)              #  Random [0,1)
print(eye)               #  Identity matrix

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.0765, 0.0338, 0.2631],
        [0.9296, 0.2889, 0.3943]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [12]:
# 3. Arithmetic Operations
print(x * 2)             #  Multiply each element by 2
print(x + 1)             #  Add 1 to each element
print(x ** 2)            #  Element-wise square

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
tensor([[2., 3., 4.],
        [5., 6., 7.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


In [13]:
# 4. Comparison
print(x > 2)             #  tensor([[False, False,  True],
                        #             [ True,  True,  True]])

tensor([[False, False,  True],
        [ True,  True,  True]])


In [14]:
# 5. Broadcasting
b = torch.tensor([1., 0., 1.])  # Shape: (3,)
print(x + b)             #  Broadcasted row-wise addition

tensor([[2., 2., 4.],
        [5., 5., 7.]])


In [15]:
# 6. Reduction operations
print(x.sum())           #  Sum of all elements: 21.
print(x.sum(dim=0))      #  Column-wise sum: tensor([5., 7., 9.])
print(x.sum(dim=1))      #  Row-wise sum: tensor([6., 15.])

tensor(21.)
tensor([5., 7., 9.])
tensor([ 6., 15.])


In [19]:
# 7. Stacking
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(torch.stack([a, b]))        #  creates a new dimension and stacks tensors along that dimension
print(torch.cat([a, b]))          #  combines tensors along an existing dimension, resulting in a tensor twice as long

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3, 4, 5, 6])


In [26]:
# 8. Splitting
splits = torch.chunk(x, 2, dim=0)
print(splits[0])         #  tensor([[1., 2., 3.]]), splits is a tuple

splits = torch.chunk(x, 3,dim=1)
print(splits[0])         #  tensor([[1.], [4.]]), splits is a tuple

tensor([[1., 2., 3.]])
tensor([[1.],
        [4.]])


In [27]:
# 9. Dimensionality
print(x.ndim)            #  2
print(x.shape)           #  torch.Size([2, 3])
print(x.numel())         #  Total elements: 6

2
torch.Size([2, 3])
6


In [28]:
# 10. Reshaping
reshaped = x.view(3, 2)
print(reshaped)          #  tensor([[1., 2.], [3., 4.], [5., 6.]])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [ ]:
# 11. Flatten and unsqueeze
print(x.flatten())       #  tensor([1., 2., 3., 4., 5., 6.])
print(x.unsqueeze(0))    #  Add batch dim → shape: (1, 2, 3) when working with a single sample
print(x.unsqueeze(-1))   #  Add feature dim → shape: (2, 3, 1) at the end in time series or sequence models

tensor([1., 2., 3., 4., 5., 6.])
tensor([[[1., 2., 3.],
         [4., 5., 6.]]])
tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]])


In [30]:
# 12. Type casting
x_int = x.int()
print(x_int)             #  tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [ ]:
# 13. In-place operation

# An in-place operation directly modifies the data of a tensor without creating a new copy.
# In PyTorch, in-place operations are marked with an underscore (_) at the end of the method name.

# Memory efficient but can interfere with autograd, not always safe during backpropagation (can overwrite values needed for gradients)

x_clone = x.clone()
x_clone.add_(1)
print(x_clone)           #  Values incremented in-place

In [2]:
import timeit
import torch
 
x = torch.rand(2**11, 2**11) 
time_cpu = timeit.timeit("x@x", globals=globals(), number=100)

In [3]:
# Choose GPU device
print("Is CUDA available? :", torch.cuda.is_available()) 
device = torch.device("cuda") 

Is CUDA available? : True


In [4]:
x = x.to(device) 
time_gpu = timeit.timeit("x@x", globals=globals(), number=100)

In [5]:
# To convert GPU tensors back to Numpy arrays, first call .cpu() to transfer the tensor back to the CPU, then call .numpy()
x_cpu = x.cpu().numpy()

In [7]:
print (time_cpu, time_gpu)

5.176167199999998 0.10604759999999658


In [ ]:
# Create a tensor and track its gradient

# Create a tensor with requires_grad set to True
x = torch.randn(3, 3, requires_grad=True)  # Example tensor

# Define a simple function to minimize
y = x**2 + 3*x + 5  # Example quadratic function

# Now we can compute the gradients
# A common pitfall is attempting to compute gradients on non-scalar outputs without specifying how to reduce them
y.sum().backward()  # Computes the gradient of the sum of y

# Gradients are now stored in x.grad
print(x.grad)  # This will give the gradient of y with respect to x

tensor([[-2.0096,  3.4394,  3.4887],
        [ 1.6035,  1.1844,  6.3094],
        [-0.0747,  4.4218,  1.2055]])
